Tutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^maps/', include('maps.urls', namespace="maps")),
    # url(r'^management/', include('admin_management.urls', namespace="admin_management")),
    url(r'^', include('user_management.urls', namespace="user_management")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maps/urls.py
from django.conf.urls import url

from maps.views import *

urlpatterns = [
    url(r'^create$', map_create, name="map_create"),
    url(r'^all$', map_all, name="all"),
    url(r'^(?P<map_id>[0-9]+)/lesson/create/$', lesson_create, name="lesson_create"),
    url(r'^(?P<map_id>[0-9]+)/lessons/$', lessons_list, name='lessons'),
    url(r'^(?P<map_id>[0-9]+)/lesson/(?P<lesson_id>\d+)/$', lesson_page, name='lesson_page'),
    url(r'^(?P<map_id>[0-9]+)/lesson/(?P<lesson_id>\d+)/question/create/$', question_create, name='question_create'),
    url(r'^(?P<map_id>[0-9]+)/lesson/(?P<lesson_id>\d+)/questions/$', question_list, name='questions'),
    url(r'^(?P<map_id>[0-9]+)/lesson/(?P<lesson_id>\d+)/test/$', lesson_test, name='lesson_test'),

]

user_management/urls.py
from django.conf.urls import url
from user_management.views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^registration$', user_registretion, name="registration"),
    url(r'^profile/', profile, name="profile"),
    url(r'^login/', login_view, name="login"),
    url(r'^logout$', auth_views.logout, {'next_page': '/login'}, name='logout'),
]

user_management/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class SimpleUser(models.Model):
    class Meta:
        verbose_name = u'пользователь'
        verbose_name_plural = u'пользователи'
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name=u'пользователь')
    second_name = models.CharField(max_length=40, verbose_name=u'фамилия')
    moder = models.BooleanField(default=False, verbose_name=u'модератор')

    def __str__(self):
        return '%s %s' % (self.user.first_name, self.second_name)

user_management/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.contrib.auth.hashers import make_password, check_password


# Create your views here.
from django.urls import reverse

from user_management.helpers import validator
from user_management.models import SimpleUser
from maps.models import *


def registration(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        second_name = request.POST['second_name']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        args = {'first_name': first_name, 'second_name': second_name, 'email': email}
        if not validator.is_fields_filled(email, first_name, second_name, password, confirm_password):
            args['error'] = 'Please fill in all fields'
        elif not validator.is_correct_email(email):
            args['error'] = 'Invalid mail format'
        elif not validator.is_email_free(email):
            args['error'] = 'User with this mail already exists'
        elif not validator.is_correct_password(password):
            args['error'] = 'Invalid password format'
        elif not validator.is_passwords_match(password, confirm_password):
            args['error'] = 'Passwords don\'t match'
        elif not validator.is_correct_name(first_name, second_name):
            args['error'] = 'Invalid name format'

        if args.get('error'):
            return args

        user = User(username=email,
                    password=make_password(password, salt=None, hasher='default'),
                    first_name=first_name)

        user.save()
        simple_user = SimpleUser(user=user, second_name=second_name)
        simple_user.save()
        return simple_user


def user_registretion(request):
    if request.method == "POST":
        result = registration(request)
        if isinstance(result, SimpleUser):
            return HttpResponseRedirect(reverse('user_management:login'))
        else:
            return render(request, "user_management/registration.html", result)

    else:
        return render(request, "user_management/registration.html")


def login_view(request):
    if not request.user.is_anonymous:
        return HttpResponseRedirect('/profile/')
    user = request.user
    if request.method == 'POST':
        user = authenticate(
            username=request.POST['username'],
            password=request.POST['password']
        )
        if user is not None:
            login(request, user, backend=None)
            if check_status(user) != 'company':
                return HttpResponseRedirect('/profile/')
            else:
                return HttpResponseRedirect('/company/' + user.id)
        else:
            error_message = 'User not found.' if not User.objects.filter(username=request.POST['username']).count() \
                else 'Password incorrect.'
            return render(request, 'user_management/login.html', {'error': error_message,
                                                                  'email': request.POST['username']})
    return render(request, 'user_management/login.html', {'status': check_status(user)})


def check_status(user):
    status = 'student'
    if user is None or user.is_anonymous:
        status = 'anonymous'
    elif user.is_staff:
        status = 'admin'
    return status


def profile(request, user_id=None):
    if request.user.is_anonymous():
        return HttpResponseRedirect('/login/')
    if not user_id:
        if request.user is not None:
            user_id = request.user.id
        else:
            raise Http404('You are not authenticated')
    if SimpleUser.objects.filter(user=User.objects.get(id=user_id)).count():
        user = SimpleUser.objects.get(user=User.objects.get(id=user_id))
        user_lesson = UserLesson.objects.filter(user=user)
    else:
        raise Http404('User with id %s not found.' % user_id)
    return render(request, 'user_management/profile.html',
                  {'user': user, 'results' : user_lesson})

user_management/templates/user_management/login.html
{% extends 'maps/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="text">
            <span>Данный сайт разработат в раках лаборатории КФУ</span>
            <span>факультета ВШ ИТИС. Руководитель М,М. Абрамский.</span>
            <span>Ознакомится с программой обучения вы можете <a class="link_green">тут.</a></span>
            <span>Чтобы начать обучение необходимо <a class="link_green" data-target="#modal_login" data-toggle="modal">войти</a> или <a class="link_green" href="{% url 'user_management:registration' %}">зарегистрироваться.</a></span>
        </div>
    </div>
{% endblock %}
{% block footer%}footer{% endblock %}

user_management/templates/user_management/profile.html
{% extends 'maps/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="profile_info">
            <div class="profile_name">
                <div id="profileImage"></div>
                <span id="firstName">{{ user.user.first_name }}</span> <span id="lastName">{{ user.second_name }}</span>
            </div>
            <span class="ps_text">{{ user.user.email_user }}</span>
        </div>

    <div class="results">
        <ul class="list_res">
            <h3 class="user_lessons_title">Список пройденных уроков</h3>
            {% for result in results %}
                <li class="user_lessons">{{ result.lesson.name }} <div class="progress">
                    <div class="progress-bar progress-bar-success" role="progressbar"
                         aria-valuenow="{{ result.percent }}" aria-valuemin="0"
                         aria-valuemax="100" style="width: {{ result.percent }}%">
                        {{ result.percent }}%
                        <span class="sr-only">{{ result.percent }}% Complete (success)</span>
                    </div>
                </div></li>

            {% endfor %}
        </ul>
    </div>
    </div>
{% endblock %}
{% block footer %}footer
{% endblock %}

user_management/templates/user_management/registration.html
{% extends 'maps/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
    <form method="post" class="reg_form">
        {% csrf_token %}
        <div class="lbl_block">
            <label>Имя</label>

            <input type="text" class="input" name="first_name">
        </div>
        <div class="lbl_block">
            <label>Фамилия</label>

            <input type="text" class="input" name="second_name">
        </div>
        <div class="lbl_block">
            <label>Email</label>

            <input type="text" class="input" name="email">
        </div>
        <div class="lbl_block">
            <label>Пароль</label>

            <input type="password" class="input" name="password">
        </div>
        <div class="lbl_block">
            <label>Повтор пароля</label>

            <input type="password" class="input" name="confirm_password">
        </div>
        <i style="color: red">{{ error }}</i>
        <div class="text-right">
            <button type="submit" class="btn_all button_green">Зарегистрироваться</button>
        </div>
    </form>
    </div>
{% endblock %}
{% block footer%}footer{% endblock %}