Tutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^maps/', include('maps.urls', namespace="maps")),
    # url(r'^management/', include('admin_management.urls', namespace="admin_management")),
    url(r'^', include('user_management.urls', namespace="user_management")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maps/urls.py
from django.conf.urls import url

from maps.views import *

urlpatterns = [
    url(r'^create$', map_create, name="map_create"),
    url(r'^all$', map_all, name="all"),
    url(r'^(?P<map_id>[0-9]+)/lesson/create/$', lesson_create, name="lesson_create"),
    url(r'^(?P<map_id>[0-9]+)/lessons/$', lessons_list, name='lessons'),
    url(r'^(?P<map_id>[0-9]+)/lesson/(?P<lesson_id>\d+)/$', lesson_page, name='lesson_page'),
    url(r'^(?P<map_id>[0-9]+)/lesson/(?P<lesson_id>\d+)/question/create/$', question_create, name='question_create'),
    url(r'^(?P<map_id>[0-9]+)/lesson/(?P<lesson_id>\d+)/questions/$', question_list, name='questions'),
    url(r'^(?P<map_id>[0-9]+)/lesson/(?P<lesson_id>\d+)/test/$', lesson_test, name='lesson_test'),

]

user_management/urls.py
from django.conf.urls import url
from user_management.views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^registration$', user_registretion, name="registration"),
    url(r'^profile/', profile, name="profile"),
    url(r'^login/', login_view, name="login"),
    url(r'^logout$', auth_views.logout, {'next_page': '/login'}, name='logout'),
]

maps/models.py
import datetime
from django.db import models

# Create your models here.
from user_management.models import SimpleUser


class Map(models.Model):
    class Meta:
        verbose_name = u'карта'
        verbose_name_plural = u'карты'

    name = models.CharField(max_length=40, verbose_name=u'имя')
    image = models.ImageField(default='map_images/no-img.jpg', verbose_name=u'изображение')
    them = models.CharField(max_length=40, verbose_name=u'тема')

    def __str__(self):
        return '%s %s' %(self.id, self.name)


class UserMap(models.Model):
    class Meta:
        verbose_name = u'карта пользователя'
        verbose_name_plural = u'карты пользователя'

    user = models.ForeignKey(SimpleUser, verbose_name=u'пользователь')
    map = models.ForeignKey(Map, verbose_name=u'карта')
    percent = models.IntegerField(default=0, verbose_name=u'процент')
    comlite = models.BooleanField(default=False, verbose_name=u'прохождение')


class Lesson(models.Model):
    class Meta:
        verbose_name = u'урок'
        verbose_name_plural = u'уроки'

    name = models.CharField(max_length=400, verbose_name=u'имя')
    text = models.TextField(max_length=4000, verbose_name=u'текст')
    image = models.ImageField(default='map_images/no-img.jpg', blank=True, verbose_name=u'изображение')
    map = models.ForeignKey(Map, verbose_name=u'карта')

    def __str__(self):
        return self.name

    def get_user_lesson(self):
        return UserLesson.objects.filter(lesson=self)


class UserLesson(models.Model):
    class Meta:
        verbose_name = u'урок пользователя'
        verbose_name_plural = u'уроки пользователя'

    user = models.ForeignKey(SimpleUser, verbose_name=u'пользователь')
    lesson = models.ForeignKey(Lesson, verbose_name=u'урок')
    percent = models.IntegerField(default=0, verbose_name=u'процент')
    comlite = models.BooleanField(default=False, verbose_name=u'прохождение')

    def __str__(self):
        return '%s %s' %('урок пользователя к уроку', self.lesson.id)


class Chain(models.Model):
    class Meta:
        verbose_name = u'цепь'
        verbose_name_plural = u'цепи'

    lesson_child = models.ForeignKey(Lesson, verbose_name=u'наследник', related_name='child')
    lesson_parent = models.ForeignKey(Lesson, verbose_name=u'родитель', related_name='parent')

    def __str__(self):
        return '%s <- [%s]' %(self.lesson_parent.id, self.lesson_child.id)


class Question(models.Model):
    class Meta:
        verbose_name = u'вопрос'
        verbose_name_plural = u'вопросы'

    text = models.TextField(max_length=400, verbose_name=u'текст')
    lesson = models.ForeignKey(Lesson, verbose_name=u'урок пользователя')

    def __str__(self):
        return '%s %s' %('вопрос к у року', self.lesson)

    def get_choices(self):
        return ChoiceAnswer.objects.filter(question=self)


class ChoiceAnswer(models.Model):
    class Meta:
        verbose_name = u'вариант ответа'
        verbose_name_plural = u'варианты ответов'

    text = models.TextField(max_length=100, verbose_name=u'текст')
    question = models.ForeignKey(Question, verbose_name=u'вопрос')
    right = models.BooleanField(default=False, verbose_name=u'правильность')


class Test(models.Model):
    class Meta:
        verbose_name = u'тест'
        verbose_name_plural = u'тесты'

    user_lesson = models.ForeignKey(UserLesson, null=True, verbose_name=u'урок пользователя')
    date = models.DateTimeField(default=datetime.datetime.now, verbose_name=u'дата прохождения')
    def __str__(self):
        return '%s' %( self.date)


class Exam(models.Model):
    class Meta:
        verbose_name = u'экзамен'
        verbose_name_plural = u'экзамены'
    user = models.ForeignKey(SimpleUser, verbose_name=u'пользователь')
    date = models.DateTimeField(default=datetime.datetime.now, verbose_name=u'дата прохождения')


class ReadyQuestion(models.Model):
    class Meta:
        verbose_name = u'готовый вопрос'
        verbose_name_plural = u'готовые вопросы'

    test = models.ForeignKey(Test, verbose_name=u'тест')
    question = models.ForeignKey(Question, verbose_name=u'вопрос')
    right = models.BooleanField(default=False, verbose_name=u'правильность')

maps/views.py
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse

from maps.models import *


# Create your views here.

@login_required
def map_create(request):
    args = {}
    user = request.user
    simple = SimpleUser.objects.get(user=user)
    if not simple.moder:
        raise Http404
    if request.method == 'POST':
        name = request.POST['name']
        them = request.POST['them']
        args.update({'name': name, 'them': them})
        map = Map(name=name, them=them)
        map.save()
        if request.FILES.get('image'):
            image = request.FILES['image']
            fs = FileSystemStorage()
            filename = fs.save('map/' + image.name, image)
            map.image.name = filename
            map.save()
        return HttpResponseRedirect(reverse('maps:maps'))
    return render(request, 'maps/map_create.html', args)


@login_required
def map_all(request):
    if request.method == 'GET':
        user = request.user
        simple = SimpleUser.objects.get(user=user)
        if not simple.moder:
            raise Http404
        maps = Map.objects.all()
    return render(request, 'maps/all.html', {'maps': maps})


@login_required
def lesson_create(request, map_id):
    args = {}
    user = request.user
    simple = SimpleUser.objects.get(user=user)
    if not simple.moder:
        raise Http404
    map = Map.objects.get(id=map_id)
    args['map'] = map
    if request.method == 'POST':
        name = request.POST['name']
        text = request.POST['text']
        args.update({'name': name, 'text': text})
        lesson = Lesson(name=name, text=text, map=map)
        lesson.save()

        if request.FILES.get('image'):
            image = request.FILES['image']
            fs = FileSystemStorage()
            filename = fs.save('maps/' + str(map_id) + '/lesson/' + str(lesson.id) + image.name, image)
            lesson.image.name = filename
            lesson.save()
        return HttpResponseRedirect(reverse('maps:lessons', kwargs={'map_id': map_id}))
    return render(request, 'maps/lesson_create.html', args)


@login_required
def lesson_page(request, map_id, lesson_id):
    args = {}
    lesson = Lesson.objects.get(id=lesson_id)
    args['lesson'] = lesson
    args['map_id'] = map_id
    user = request.user
    simple = SimpleUser.objects.get(user=user)
    lesson_user = UserLesson.objects.filter(user=simple, lesson=lesson).first()
    parents = Chain.objects.filter(lesson_child=lesson)
    childs = Chain.objects.filter(lesson_parent=lesson)
    lessons = Lesson.objects.all()
    args['user'] = simple
    args['lesson_user'] = lesson_user
    args['parent_list'] = parents
    args['child_list'] = childs
    args['lessons'] = lessons
    if request.method == 'POST':
        lesson_parent_id = request.POST['chain_']
        lesson_parent = Lesson.objects.get(id=lesson_parent_id)
        chain = Chain(lesson_child=lesson, lesson_parent=lesson_parent)
        chain.save()
    return render(request, "maps/lesson.html", args)


@login_required
def lessons_list(request, map_id):
    if request.method == 'GET':
        lessons = [elem for elem in Lesson.objects.filter(map=Map.objects.get(id=map_id))]
        return render(request, "maps/lessons_list.html", {'lessons': lessons, 'map_id': map_id})


@login_required
def question_create(request, map_id, lesson_id):
    args = {}
    user = request.user
    simple = SimpleUser.objects.get(user=user)
    if not simple.moder:
        raise Http404
    lesson = Lesson.objects.get(id=lesson_id)
    if request.method == 'POST':
        text = request.POST['text']
        args['text'] = text
        question = Question(text=text, lesson=lesson)
        question.save()

        for i in range(1, 5):
            answer = request.POST['answer' + str(i)]
            answer = ChoiceAnswer(text=answer,
                                  question=question)
            if request.POST.get('right' + str(i)):
                answer.right = True
            answer.save()
        return HttpResponseRedirect(reverse('maps:questions', kwargs={'map_id': map_id, 'lesson_id': lesson_id}))
    return render(request, 'maps/question_create.html', args)


@login_required
def question_list(request, map_id, lesson_id):
    user = request.user
    simple = SimpleUser.objects.get(user=user)
    if not simple.moder:
        raise Http404
    lesson = Lesson.objects.get(id=lesson_id)
    questions = Question.objects.filter(lesson=lesson)
    return render(request, 'maps/questions_list.html',
                  {'questions': questions, 'map_id': map_id, 'lesson_id': lesson_id})


@login_required
def lesson_test(request, map_id, lesson_id):
    args = {}
    percent = 0
    count = 5
    args['map_id'] = map_id
    args['lesson_id'] = lesson_id
    lesson = Lesson.objects.get(id=lesson_id)
    user = request.user
    simple = SimpleUser.objects.get(user=user)
    questions = Question.objects.filter(lesson=lesson)
    if request.method == 'GET':
        args['test'] = questions
    if request.method == 'POST':
        test = Test()
        test.save()
        for i in questions:
            question_id = request.POST['question' + str(i.id)]
            ready_answer = request.POST['answer' + str(i.id)]
            right = False
            question = Question.objects.get(id=question_id)
            if ChoiceAnswer.objects.filter(id=int(ready_answer), right=True):
                right = True
                percent += 1
            ready_question = ReadyQuestion(question=question, test=test, right=right)
            ready_question.save()
        percent = (percent / count) * 100
        print(percent)
        user_lesson = UserLesson(user=simple, lesson=lesson, percent=percent, comlite=True)
        user_lesson.save()
        test = Test(user_lesson=user_lesson)
        test.save()
        return HttpResponseRedirect(reverse('maps:lesson_page', kwargs={'map_id': map_id, 'lesson_id': lesson_id}))
    return render(request, 'maps/test_page.html', args)


def get_ids(questions):
    ids = []
    for question in questions:
        ids.append(str(question.id))
    return ids

maps/templates/maps/all.html
{% extends 'maps/base.html' %}
{% load static %}
{% block content %}
    {% for map in maps %}
        {{ map.name }}
    {% endfor %}

{% endblock %}
{% block footer%}footer{% endblock %}

maps/templates/maps/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/help.css' %}" type="text/css">
    {% block links %}
    {% endblock %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'user_management:profile' %}"><img src="{% static 'img/itis.png' %}"
                                                                                    class="itis_img"></a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            {% if user.is_anonymous %}
            {% else %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'maps:lessons' 1 %}">Карта</a></li>
                </ul>
            {% endif %}
            {% if user.moder %}
                <div class="btn-group">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        Управление
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li><a href="{% url 'maps:map_create' %}">Создать карту</a></li>
                        <li><a href="{% url 'maps:lesson_create' 1 %}">Создать урок</a></li>
                        <li><a href="{% url 'maps:all' %}">Список карт</a></li>
                        {% block others %}

                        {% endblock %}
                    </ul>
                </div>
            {% endif %}
            <ul class="nav navbar-nav">
                <li>{% block chains %}
                {% endblock %}</li>
            </ul>
            {% if user.is_anonymous %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a class="button_green btn_all" href="#" data-target="#modal_login"
                           data-toggle="modal">Войти</a></li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a class="button_white btn_all" href="{% url 'user_management:logout' %}">Выйти</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>

<div class="modal fade" id="modal_login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span
                        aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <div class="title">Вход</div>
            </div>
            <form method="post" class="log_form">
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="lbl_block">
                        <label>Имя</label>
                        <input type="text" class="input" name="username">
                    </div>
                    <div class="lbl_block">
                        <label>Пароль</label>
                        <input type="password" class="input" name="password">
                    </div>
                </div>
                <div class="btn_block">
                    <button class="button_green btn_all" type="submit">Войти</button>
                    <button class="button_white btn_all" data-dismiss="modal">Закрыть</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="main-block">
    {% block content %}{% endblock %}
</div>


<div class="{% block footer %}{% endblock %}">
    <img class="kfu-logo" id="kpfu_logo" src="{% static 'img/kpfu_logo.png' %}" alt="KPFU logo">
    <h4 class="footer-text">Students Educational Project 2017</h4>
</div>

</body>
</html>

maps/templates/maps/lesson.html
{% extends 'maps/base.html' %}
{% load static %}
{% block chains %}
    <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Уроки
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            {% for chain in child_list %}
                <li><a href="{% url 'maps:lesson_page' map_id chain.lesson_child.id %}">{{ chain.lesson_child.name }}</a>
                </li>
            {% endfor %}
            {% for chain in parent_list %}
                <li>
                    <a href="{% url 'maps:lesson_page' map_id chain.lesson_parent.id %}">{{ chain.lesson_parent.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}
{% block others %}
    <li><a href="{% url 'maps:question_create' map_id lesson.id %}">Создать вопрос</a></li>
    <li><a href="{% url 'maps:questions' map_id lesson.id %}">Просмотрнть вопросы</a></li>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="lesson_title text-center">{{ lesson.name }}</div>
        <div class="lesson_trgt text-center">{% if lesson.image.url is not None %}
            <img src='{{ lesson.image.url }}' style="max-height: 100px; max-width: 100px"/>
        {% endif %}</div>
        <div class="lesson_text text-left">{{ lesson.text }}</div>
        <div class="lesson_btn text-right">
            <a href="{% url 'maps:lessons' map_id %}" class="button_white btn_all">вернуться к карте</a>
            {% if lesson_user %}
            {% else %}
                <a href="{% url 'maps:lesson_test' map_id lesson.id %}" class="button_green btn_all">Пройти тест</a>
            {% endif %}
        </div>

    </div>
    {% if lesson_user.persent %}
        <div class="lesson_title text-center">Статистика</div>
        <div class="profile_status">
            <div class="profile_subject">
                <div class="ps_current_status">{{ lesson_user.percent }}%</div>
            </div>
        </div>
    {% endif %}
    {% if user.moder %}
        <form method="post">
            {% csrf_token %}
            <label>
                <select>
                    {% for lesson in lessons %}
                        <option name="chain_" value="{{ lesson.id }}">{{ lesson.id }} {{ lesson.name }}</option>
                    {% endfor %}
                </select>
            </label>
            <button type="submit" class="button_white btn_all">Связать</button>
        </form>
    {% endif %}
{% endblock %}

{% block footer %}footer2{% endblock %}

maps/templates/maps/lesson_create.html
{% extends 'maps/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <form method="post" class="create" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="lbl_block">
                <label>Название</label><input type="text" class="input" name="name">
            </div>
            <div class="lbl_block">
                <label>Содержание</label><input type="text" class="input" name="text">
            </div>
                <label>Изображение</label><input type="file" class="input_file" name="image">
            <div class="text-right">
                <button type="submit" class="btn_all button_green">Создать</button>
            </div>
        </form>
    </div>
{% endblock %}
{% block footer%}footer{% endblock %}

maps/templates/maps/lessons_list.html
{% extends 'maps/base.html' %}
{% load static %}
{% block links %}

{% endblock %}
{% block content %}
    <div class="back">
        <div class="container">
            {% for lesson in lessons %}
                <div class="lesson_name">
                    <a href="{% url 'maps:lesson_page' map_id lesson.id %}"><img src="{{ lesson.image.url }}"
                                                                                 style="width: 200px; height: 200px">
                        <p class="ln_text"><span>{{ lesson.name }}</span></p>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block footer %}footer{% endblock %}

maps/templates/maps/map_create.html
{% extends 'maps/base.html' %}
{% load static %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <label>Название</label><input type="text" name="name"/>
        <label>Тема</label><input type="text" name="them"/>
        <label>Изображение</label><input type="file" name="image"/>
        <button type="submit" class="btn_all button_green">Создать</button>
    </form>
{% endblock %}
{% block footer%}footer{% endblock %}

maps/templates/maps/question_create.html
{% extends 'maps/base.html' %}
{% load static %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <label>Содержание вопроса</label>
        <label>
            <input type="text" name="text">
        </label>
        {% with ''|center:4 as range %}
        {% for _ in range %}
            <p>Ответ {{ forloop.counter }}
                <label>
                    <input type="checkbox" name="right{{ forloop.counter }}">
                </label>
                <label>
                    <input type="text" name="answer{{ forloop.counter }}"/>
                </label>
            </p>
        {% endfor %}
    {% endwith %}
    <button type="submit" class="btn_all button_green">Создать</button>
    </form>
{% endblock %}
{% block footer%}footer{% endblock %}

maps/templates/maps/questions_list.html
{% extends 'maps/base.html' %}
{% load static %}
{% block content %}
    {% for question in questions %}
        <span>
        {{ question.text }}
        {% for answers in question.get_choices %}
            <li>{{ answers.text }}</li>
        {% endfor %}</span>
    {% endfor %}
{% endblock %}
{% block footer%}footer2{% endblock %}

maps/templates/maps/test_page.html
{% extends 'maps/base.html' %}
{% load static %}
{% block content %}
<div class="container">
<form method="post">
    {% csrf_token %}
    <div class="test_text">
        {% for question in test %}
            <div class="test_question">{{ question.text }}</div>
            <input type="hidden" name="question{{ question.id }}" value="{{ question.id }}">
            <div class="test_answer text-left">
                {% for answer in question.get_choices %}
                    <label for="answer{{ question.id }}">
                        <input type="radio" name="answer{{ question.id }}" id="answer{{ question.id }}" value="{{ answer.id }}">{{ answer.text }}</label>

                {% endfor %}
            </div>

        {% endfor %}
        <div class="test_btns text-right">
            <label>
                <button type="submit" class="button_green btn_all">Завершить тест</button>
            </label>
            <a href="{% url 'maps:lesson_page' map_id lesson_id %}" class="button_white btn_all">Вернуться к уроку</a>
        </div>
    </div>
</form>
</div>
{% endblock %}
{% block footer%}footer2{% endblock %}